inhours_primary:
  value: 1
  weekdays: true
  weeknights: false
  weekends: false
  pagerduty:
    schedule_name: GOV.UK Primary (1st Call)
    schedule_id: P479TSJ
inhours_secondary:
  value: 1
  weekdays: true
  weeknights: false
  weekends: false
  pagerduty:
    schedule_name: GOV.UK Secondary (2nd Call)
    schedule_id: P752O37
oncall_primary:
  value: 1
  weekdays: false
  weeknights: true
  weekends: true
  pagerduty:
    schedule_name: GOV.UK Primary (1st Call)
    schedule_id: P479TSJ
oncall_secondary:
  value: 1
  weekdays: false
  weeknights: true
  weekends: true
  pagerduty:
    schedule_name: GOV.UK Secondary (2nd Call)
    schedule_id: P752O37
